---
layout: post
---

* GNU/Linux
** Emacs keybindings everywhere
*** GTK
https://wiki.archlinux.org/index.php/GTK+#Emacs_key_bindings
**** Gtk3
$ gsettings set org.gnome.desktop.interface gtk-key-theme "Emacs"

If you have Anaconda installed, make sure your path points to your system gsettings not Anaconda’s gsettings.
**** Gtk2
#+BEGIN_SRC bash
gconftool-2 --type=string --set /desktop/gnome/interface/gtk_key_theme Emacs
#+END_SRC

~/.gtkrc-2.0
gtk-key-theme-name = "Emacs"
**** XFCE
$ xfconf-query -c xsettings -p /Gtk/KeyThemeName -s Emacs
*** Chromium/Google Chrome
in “/home/zds/.config/gtk-3.0/settings.ini/” add this line:
gtk-key-theme-name=Emacs
** Desktop environment
*** Xfce
** Emacs
*** recommended compilation flags
** Terminal emulator
** Shell
*** bash
*** zsh
** input devicess
*** keyboard
**** fast repeat, low repeat delay
$ xset r rate [delay ms] [rate]
Recommended: xset r rate 160 180
*** mouse
**** high acceleration 
* macOS
** input devices
*** keyboard
**** fast repeat, low repeat delay
$ defaults write -g KeyRepeat -int 1
$ defaults write -g InitialKeyRepeat -int 10
** Emacs
*** Emacs Daemon
These instructions work as of macOS High Sierra (version 10.14) to run Emacs as a daemon on login. You can quickly run emacsclient instances without waiting for Emacs to start up.
**** Create an Apple Script with “Script Editor.app”
~/Applications/Emacs Daemon.app:
do shell script "/Applications/Emacs.app/Contents/MacOS/Emacs --daemon"
**** Add “Emacs Daemon.app" to autostart.
System Preferences → Users & Groups → choose your user → Login Items
**** Create an Apple Script for the client.
“~/Applications/Emacs Client.app”:
do shell script "/Applications/Emacs.app/Contents/MacOS/bin/emacsclient -nc"
* Windows
** keyboard repeat speed
*** TODO find and publish the source of that Windows.h-calling code that changes keyboard repeat speed on Windows
* Chromium / Google Chrome
** Recommended chrome://flags
** How to use the KDE file picker instead of the default GTK file picker
The default file picker is the ugly GTK file picker, which can’t show thumbnails for images. The KDE file picker, kdialog, is much better; it has thumbnails and sorting abilities. Chrom{e, ium} won’t use kdialog unless you run it like this:

#+BEGIN_SRC bash
$ env XDG_CURRENT_DESKTOP=KDE chromium-browser
#+END_SRC

You can either modify Chromium’s .desktop entry to run this command or make this script:

#+BEGIN_SRC bash
#!/bin/sh

export XDG_CURRENT_DESKTOP=KDE
exec chromium-browser "$@"
#+END_SRC
* Emacs
- See my dotfiles/emacs.d repo
- Take advantage of Language Server Protocol.
* Hardware
** Reduce blue light from monitors
Blue light is [[https://phys.org/news/2018-08-chemists-blue.html][harmful and permanently damaging to your retinas]].
1. Toggle the on-screen menu.
2. Find the screen for colors or color management.
3. Set any and all of these to 0
   1. blue
   2. cyan
   3. magenta
